### ISSUE TITLE
Invalid redirection target:

### ISSUE THREAD

**Issue by TripShade** [jorgebucaran/nvm.fish#155] opened 2021-04-19 18:08 UTC
When i try nvm install or nvm list-remote i get the following error.
```sh
/usr/share/fish/vendor_functions.d/_nvm_index_update.fish (line 7): Invalid redirection target:
' >$index.temp 2>/dev/null && command mv $index.temp $index && return
^
in function '_nvm_index_update'
called on line 148 of file /usr/share/fish/vendor_functions.d/nvm.fish
in function 'nvm' with arguments 'ls-remote'
nvm: Invalid index or unavailable host: ""
```

Both Aur package of NVM and install script from nvm-sh/nvm github result in this error.

System specs:
```sh
x;XxXB%89b8:b8%b88:            --------------------------
.8Xxd                8X:.         OS: Garuda Linux x86_64
.8Xx;                    8x:.       Kernel: 5.11.8-zen1-1-zen
.tt8x          .d            x88;     Uptime: 57 mins
.@8x8;          .db:              xx@;   
,tSXX°          .bbbbbbbbbbbbbbbbbbbB8x@;  Packages: 1863 (pacman)
.SXxx            bBBBBBBBBBBBBBBBBBBBbSBX8;  Shell: fish
,888S                                     pd!  Resolution: 3840x1080
8X88/                                       q   Terminal: konsole
GBB.                                            
x%88        d888@8@X@X@X88X@@XX@@X@8@X.        CPU: Intel i5-6600K (4) @ 3.9GHz
dxXd    dB8b8b8B8B08bB88b998888b88x.         Memory: 2150MiB / 23960MiB (8%)
dxx8o                      .@@;.            
dx88                   .t@x.                                      
d:SS@8ba89aa67a853Sxxad.                                        
.d988999889889899dd.  
```

**Comment by jorgebucaran** [comment] 2021-04-19 23:28
Seems like a dupe of https://github.com/jorgebucaran/nvm.fish/issues/140. Uninstall and then reinstall nvm.

**Closed as completed by jorgebucaran** 2021-04-19 23:28 UTC
